// Keep Swiftlight's native library distinct from a local MoonlightAppleVideo
// package that also embeds PyroWave. Apply before both native and bridge headers.
#ifndef SWIFTLIGHT_PYROWAVE_SYMBOLS_H
#define SWIFTLIGHT_PYROWAVE_SYMBOLS_H
#define PyroWave SwiftlightPyroWave
#define pyrowave_chroma_subsampling swiftlight_pyrowave_chroma_subsampling
#define pyrowave_cpu_buffer swiftlight_pyrowave_cpu_buffer
#define pyrowave_cpu_buffer_format swiftlight_pyrowave_cpu_buffer_format
#define pyrowave_create_default_device swiftlight_pyrowave_create_default_device
#define pyrowave_decoder swiftlight_pyrowave_decoder
#define pyrowave_decoder_clear swiftlight_pyrowave_decoder_clear
#define pyrowave_decoder_create swiftlight_pyrowave_decoder_create
#define pyrowave_decoder_create_info swiftlight_pyrowave_decoder_create_info
#define pyrowave_decoder_decode_gpu_buffer swiftlight_pyrowave_decoder_decode_gpu_buffer
#define pyrowave_decoder_decode_is_ready swiftlight_pyrowave_decoder_decode_is_ready
#define pyrowave_decoder_decode_is_ready_with_sideband swiftlight_pyrowave_decoder_decode_is_ready_with_sideband
#define pyrowave_decoder_destroy swiftlight_pyrowave_decoder_destroy
#define pyrowave_decoder_opaque swiftlight_pyrowave_decoder_opaque
#define pyrowave_decoder_push_packet swiftlight_pyrowave_decoder_push_packet
#define pyrowave_device swiftlight_pyrowave_device
#define pyrowave_device_create swiftlight_pyrowave_device_create
#define pyrowave_device_create_info swiftlight_pyrowave_device_create_info
#define pyrowave_device_destroy swiftlight_pyrowave_device_destroy
#define pyrowave_device_is_supported swiftlight_pyrowave_device_is_supported
#define pyrowave_device_opaque swiftlight_pyrowave_device_opaque
#define pyrowave_encoder swiftlight_pyrowave_encoder
#define pyrowave_encoder_compute_block_active_words swiftlight_pyrowave_encoder_compute_block_active_words
#define pyrowave_encoder_compute_num_critical_packets swiftlight_pyrowave_encoder_compute_num_critical_packets
#define pyrowave_encoder_compute_num_packets swiftlight_pyrowave_encoder_compute_num_packets
#define pyrowave_encoder_compute_num_packets_with_padding swiftlight_pyrowave_encoder_compute_num_packets_with_padding
#define pyrowave_encoder_create swiftlight_pyrowave_encoder_create
#define pyrowave_encoder_create_info swiftlight_pyrowave_encoder_create_info
#define pyrowave_encoder_destroy swiftlight_pyrowave_encoder_destroy
#define pyrowave_encoder_encode_cpu_synchronous swiftlight_pyrowave_encoder_encode_cpu_synchronous
#define pyrowave_encoder_encode_gpu_synchronous swiftlight_pyrowave_encoder_encode_gpu_synchronous
#define pyrowave_encoder_get_mapped_raw_bitstream swiftlight_pyrowave_encoder_get_mapped_raw_bitstream
#define pyrowave_encoder_get_num_active_blocks swiftlight_pyrowave_encoder_get_num_active_blocks
#define pyrowave_encoder_opaque swiftlight_pyrowave_encoder_opaque
#define pyrowave_encoder_packetize swiftlight_pyrowave_encoder_packetize
#define pyrowave_encoder_packetize_with_padding swiftlight_pyrowave_encoder_packetize_with_padding
#define pyrowave_get_api_version swiftlight_pyrowave_get_api_version
#define pyrowave_gpu_buffers swiftlight_pyrowave_gpu_buffers
#define pyrowave_gpu_input swiftlight_pyrowave_gpu_input
#define pyrowave_iosurface swiftlight_pyrowave_iosurface
#define pyrowave_message_cb swiftlight_pyrowave_message_cb
#define pyrowave_mtl_command_buffer swiftlight_pyrowave_mtl_command_buffer
#define pyrowave_mtl_device swiftlight_pyrowave_mtl_device
#define pyrowave_mtl_texture swiftlight_pyrowave_mtl_texture
#define pyrowave_packet swiftlight_pyrowave_packet
#define pyrowave_rate_control swiftlight_pyrowave_rate_control
#define pyrowave_result swiftlight_pyrowave_result
#define pyrowave_result_to_string swiftlight_pyrowave_result_to_string
#endif
