#!/usr/bin/env python3
"""Regenerate synthetic redistributable HEVC/AV1 fixtures with the decoder's encoder tool.

An encoder is a development-only dependency; no encoder/reference decoder links into
Swiftlight. Existing committed fixtures need no regeneration or external tools.
"""
import argparse
import hashlib
import json
import pathlib
import subprocess

ROOT = pathlib.Path(__file__).resolve().parents[1]
PIN = "8d92ee039dc19fe50dc0158d5098d4c5646c6a56"


def sha(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--decoder", type=pathlib.Path, default=ROOT.parent / "moonlight-apple-decoder")
    parser.add_argument("--generator", type=pathlib.Path)
    parser.add_argument("--aomenc", type=pathlib.Path)
    args = parser.parse_args()
    decoder = args.decoder.resolve()
    revision = subprocess.check_output(["git", "-C", str(decoder), "rev-parse", "HEAD"], text=True).strip()
    if revision != PIN:
        raise SystemExit(f"Decoder fixture source must be pinned to {PIN}, found {revision}")
    generator = (args.generator or decoder / "build/mav-fixture").resolve()
    aomenc = (args.aomenc or decoder / ".local/aom-build/aomenc").resolve()
    if not generator.is_file() or not aomenc.is_file():
        raise SystemExit("Build mav-fixture and run the decoder's scripts/bootstrap-aom.sh first; see docs/dev/video-validation.md")
    commands = []
    configurations = [(codec, variant, 128, 72, f"{codec}-{variant}") for codec in ("hevc", "av1") for variant in ("sdr8", "hdr10")]
    configurations += [(codec, "hdr10", 192, 104, f"{codec}-reconfigure") for codec in ("hevc", "av1")]
    for codec, variant, width, height, name in configurations:
        output = ROOT / "fixtures" / name
        command = [str(generator), "--codec", codec, "--variant", variant, "--width", str(width), "--height", str(height),
                   "--fps", "60", "--frames", "8", "--gop", "4", "--output", str(output)]
        if codec == "av1":
            command.extend(["--aomenc", str(aomenc)])
        subprocess.run(command, check=True)
        commands.append({"fixture": output.name, "arguments": command[1:], "manifest_sha256": sha(output / "manifest.json"),
                         "payload_sha256": sha(output / "payload.bin")})
    provenance = {"source": "Synthetic moving-gradient-detail-square-frame-id-v1 generated by mav-fixture",
                  "decoder_revision": revision, "generator_binary_sha256": sha(generator), "aomenc_binary_sha256": sha(aomenc),
                  "copyright": "Generated synthetic test patterns; distributed under this repository's GPL-3.0 license.",
                  "note": "HEVC hardware encoding is OS-versioned and need not reproduce identical compressed bytes. Manifests describe exact saved bytes.",
                  "fixtures": commands}
    (ROOT / "fixtures/provenance.json").write_text(json.dumps(provenance, indent=2) + "\n")


if __name__ == "__main__":
    main()
